apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zapier-webhook
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
spec:
  rules:
    - host: your-domain.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zapier-webhook
                port:
                  number: 80
  tls:
    - hosts:
        - your-domain.example
      secretName: your-tls-secret


