apiVersion: v1
kind: Service
metadata:
  name: zapier-webhook
  labels:
    app: zapier-webhook
spec:
  selector:
    app: zapier-webhook
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP


